# Generated by Django 5.1.7 on 2025-03-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_remove_currencycode_company_code_and_more'),
        ('report', '0002_remove_reportconfiguration_filters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportconfiguration',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.bank'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='bank_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.bankbranch'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='credit_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.creditfacilitymaster'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='curr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.currencycode'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='curr_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.currencyrate'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='gl_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.glchartofaccount'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.maincategory'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.partie'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.project'),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.subcategory'),
        ),
    ]
