# Generated by Django 5.1.7 on 2025-03-14 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.IntegerField(unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=10)),
                ('document_types', models.BooleanField(default=False)),
                ('main_categories', models.BooleanField(default=False)),
                ('sub_categories', models.BooleanField(default=False)),
                ('projects', models.BooleanField(default=False)),
                ('parties', models.BooleanField(default=False)),
                ('gl_coa', models.BooleanField(default=False)),
                ('banks', models.BooleanField(default=False)),
                ('bank_branches', models.BooleanField(default=False)),
                ('credit_facility_master', models.BooleanField(default=False)),
                ('filter1', models.BooleanField(default=False)),
                ('sub_filter1', models.BooleanField(default=False)),
                ('filter2', models.BooleanField(default=False)),
                ('sub_filter2', models.BooleanField(default=False)),
                ('currency_codes', models.BooleanField(default=False)),
                ('currency_rates', models.BooleanField(default=False)),
                ('number_of_licenses_purchased', models.IntegerField()),
                ('number_of_licenses_used', models.IntegerField(default=0)),
                ('concurrent_users_now', models.IntegerField(default=0)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('town_city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=150)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=150)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('parent_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
        ),
    ]
