# Generated by Django 5.1.7 on 2025-03-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='bank_branches',
            new_name='banks_branches',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='currency_codes',
            new_name='curr_codes',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='currency_rates',
            new_name='curr_rates',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='gl_coa',
            new_name='gl_chart_of_accounts',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='concurrent_users_now',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_licenses_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_licenses_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
