# Generated by Django 5.1.7 on 2025-03-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_bank_branches_company_banks_branches_and_more'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='company_code',
        ),
        migrations.AddField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
