# Generated by Django 5.1.7 on 2025-03-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_bank_branches_company_banks_branches_and_more'),
        ('master', '0003_alter_bank_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='company.company'),
        ),
    ]
