# Generated by Django 5.1.7 on 2025-03-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_bank_branches_company_banks_branches_and_more'),
        ('master', '0007_remove_doctype_company_code_doctype_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glchartofaccount',
            name='company_code',
        ),
        migrations.AddField(
            model_name='glchartofaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gl', to='company.company'),
        ),
    ]
