# Generated by Django 5.1.7 on 2025-03-15 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_bank_branches_company_banks_branches_and_more'),
        ('master', '0016_remove_bankbranch_company_code_bankbranch_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditfacilitymaster',
            name='company_code',
        ),
        migrations.AddField(
            model_name='creditfacilitymaster',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditfacility', to='company.company'),
        ),
        migrations.AddField(
            model_name='filter1',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter1s', to='company.company'),
        ),
        migrations.AlterField(
            model_name='creditfacilitymaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditfacilitymaster',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filter1',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter1_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filter1',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter1_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
