# Generated by Django 5.1.7 on 2025-03-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_remove_creditfacilitymaster_company_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter1',
            name='company_code',
        ),
    ]
