# Generated by Django 5.1.7 on 2025-03-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_bank_branches_company_banks_branches_and_more'),
        ('master', '0019_alter_filter1_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencycode',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='filter2',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='subfilter1',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='subfilter2',
            name='company_code',
        ),
        migrations.AddField(
            model_name='currencycode',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currcodes', to='company.company'),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currrates', to='company.company'),
        ),
        migrations.AddField(
            model_name='filter2',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter2s', to='company.company'),
        ),
        migrations.AddField(
            model_name='subfilter1',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfilter1s', to='company.company'),
        ),
        migrations.AddField(
            model_name='subfilter2',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfilter2s', to='company.company'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankbranches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditfacilitymaster',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditfacility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencycode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currcodes_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencycode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currencycode',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currcodes_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencycode',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currencycode',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currcodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currrates_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currrates_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currrates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filter2',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter2_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filter2',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter2_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filter2',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glchartofaccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glchartofaccount',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glchartofaccount',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partie',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party', to='company.company'),
        ),
        migrations.AlterField(
            model_name='partie',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subfilter1',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfilter1_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subfilter1',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfilter1_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subfilter1',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfilter1s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subfilter2',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfilter2_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subfilter2',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfilter2_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subfilter2',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfilter2s', to=settings.AUTH_USER_MODEL),
        ),
    ]
