"""
Django settings for crpedge project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = [
    'crp-backend.onrender.com',  # Add your Render domain here
    '127.0.0.1',
    'localhost',
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'master',
    'authentication_app',
    'company',
    'transactions',
    'report',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'session_security',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'session_security.middleware.SessionSecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
]
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SECURITY_INSECURE = True
# Session Expiry Time (Inactivity timeout)
SESSION_COOKIE_AGE = 3600  # 1 hour
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists even after closing the browser
SESSION_SECURITY_WARN_AFTER = 1500  # Warn user after 25 minutes of inactivity
SESSION_SECURITY_EXPIRE_AFTER = 1800  # Logout after 30 minutes of inactivity
ROOT_URLCONF = 'crpedge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':   [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crpedge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# DATABASES = {
#     "default": {
#         "ENGINE": config("DB_ENGINE", default='django.db.backends.postgresql'),
#         "NAME": config("DB_NAME"),
#         "USER": config("DB_USER"),
#         "PASSWORD": config("DB_PASSWORD"),
#         "HOST": config("DB_HOST", default="localhost"),
#         "PORT": config("DB_PORT", default="3306"),
#     }
# }
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    )
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),
#     }
# }
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Customize the number of items per page
}
#
# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = ''
JAZZMIN_SETTINGS = {
    "site_title": "CRP Admin",
    "site_header": "Cash Resource Planning",
    "site_brand": "CRP Dashboard",
    "welcome_sign": "Welcome to the Cash Resource Planning System",
    "copyright": "CRP System © 2025",
    "search_model": ["auth.User", "company.Company"],

    # Top navigation menu (optional)
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
"theme": "superhero",

    # Sidebar visibility
    "show_sidebar": True,
    "navigation_expanded": False,  # Sidebar collapsed by default
     "show_ui_builder": True,
    # Hide all models from the dashboard to show only apps
    "hide_models": "*",  # Hides all models from the dashboard view

    # Grouping apps without showing individual models on the main page
    "order_with_respect_to": [
        "authentication",
        "transactions",
        "company",
        "master",
        "report",
        "admin.LogEntry",
    ],

    # Collapsible and clickable app links
    "collapsible_apps": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "authentication": "fas fa-lock",
        "transactions": "fas fa-exchange-alt",
        "company": "fas fa-building",
        "master": "fas fa-database",
        "report": "fas fa-file-alt",
        "admin.LogEntry": "fas fa-history",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",
}

# JAZZMIN_SETTINGS = {
#
#     "site_title": "CRP Admin",
#     "site_header": "Cash Resource Planning",
#     "welcome_sign": "Welcome to CRP Admin",
#     "show_sidebar": True,
#     "navigation_expanded": False,  # Collapse the sidebar by default
#
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#     },
#     "show_ui_builder": True,
#
#     "hide_apps": [],  # Keep all apps visible
#     "hide_models": [],
#
#     # Collapsible menu structure
#     "order_with_respect_to": [
#         "auth",
#         "crp_admin",
#         "masters",
#         "transactions",
#         "reports",
#         "payments",
#     ],
#
#     "custom_links": {
#         "masters": [{
#             "name": "Master Data",
#             "url": "admin:app_list",
#             "icon": "fas fa-database",
#             "permissions": ["masters.view_master"],
#         }],
#     },
#     "theme": "DARKLY",
#     "dark_mode_theme": "cyborg",
#    "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#         "master": "fas fa-database",
#         "company": "fas fa-building",
#     },
#
#     # Collapsible section configuration
#     "side_menu_items": [
#         {
#             "app": "masters",
#             "label": "Master",
#             "icon": "fas fa-cogs",
#             "models": [
#                 "masters.bankbranches",
#                 "masters.banks",
#                 "masters.creditfacilitymasters",
#                 "masters.currencycodes",
#                 "masters.currencyrates",
#                 "masters.doctypes",
#                 "masters.filter1s",
#                 "masters.filter2s",
#                 "masters.glchartofaccounts",
#                 "masters.maincategorys",
#                 "masters.parties",
#                 "masters.projects",
#                 "masters.subcategorys",
#                 "masters.subfilter1s",
#             ],
#         },
#         {
#             "app": "auth",
#             "label": "Authentication",
#             "icon": "fas fa-users",
#             "models": ["auth.user", "auth.group"],
#         },
#
#     ],
# }
